#!/usr/bin/sh

SPACESHIP_PROMPT_ORDER=(
  dir
  git
  char
)

SPACESHIP_PROMPT_ADD_NEWLINE=false
SPACESHIP_DIR_TRUNC=1
SPACESHIP_GIT_PREFIX=""
SPACESHIP_GIT_SYMBOL=""
SPACESHIP_GIT_BRANCH_PREFIX=""
SPACESHIP_CHAR_SYMBOL="❯ "
