#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# BSPWM Configuration
bspc monitor -d 1 2 3 4 5

bspc config border_width          2
bspc config window_gap            4
bspc config top_padding           0
bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config automatic_scheme      alternate

# bspwm colors
bspc config normal_border_color		"#404552"
bspc config focused_border_color	"#5294e2"
bspc config presel_feedback_color	"#404552"
bspc config urgent_border_color 	"#f27835"

# Rules for desktop 1
bspc rule -a Firefox           desktop=1 follow=on
bspc rule -a Google-chrome     desktop=1 follow=on
bspc rule -a Opera             desktop=1 follow=on
bspc rule -a Chromium          desktop=1 follow=on

# Rules for desktop 2
bspc rule -a Subl              desktop=2 follow=on
bspc rule -a Atom              desktop=2 follow=on
bspc rule -a code-oss          desktop=2 follow=on

# Rules for desktop 3
bspc rule -a figma-linux       desktop=3 follow=on
bspc rule -a Gimp              desktop=3 follow=on state=floating

# Rules for desktop 4
bspc rule -a Spotify           desktop=4 follow=on
bspc rule -a Vlc               desktop=4 follow=on state=fullscreen

# Rules for desktop 5
bspc rule -a VirtualBox        desktop=5 follow=on state=floating

# Floating windows
bspc rule -a Arandr               state=floating
bspc rule -a Qalculate-gtk        state=floating
bspc rule -a Pavucontrol          state=floating
bspc rule -a Pcmanfm              state=floating
bspc rule -a "VirtualBox Machine"   state=floating
bspc rule -a Sxiv                 state=floating
bspc rule -a Leafpad              state=floating
bspc rule -a Lightdm-gtk-greeter-settings state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a Transmission-gtk state=floating

# Autostart

# Default programs at start
~/.config/polybar/launch.sh &
setxkbmap es &
nm-applet &
volumeicon &
numlockx &
/usr/bin/lxpolkit &
light-locker &
udiskie -Nt &
feh --bg-fill ~/Pictures/Wallpapers/the_simpsons.jpg &
picom -bf &
dunst &

